sudo: false
language: python
python:
- '2.7'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: jonnyd
  password:
    secure: sECRdzAHsVl710J6mfatinCugdaPPOfO5JtllwHoa9tPI3/DdJs+0EAEMA0GMK3j5UemJblh/JUJLGZapmJ0HP4u1mfqcS4loSJEcE4PwmJSo6UfCJ7LpevD2R0slOa1H0997cjaUDeY4K0bhIgeOhjDxH4pMELS1YMuwv04fuaEzPMxS9GyFvhh96iGkBwtGgNcN2lcZEEiHdcOa2ezKa1JlGB7rMXi7wEZYGtEIH3y4kkIJiAfGzqQewMM/xzEahvEZlLBS/i5S+Eu7lMP9WOLKWmJY5/mLA5t9PAz/2lV2odRjs5PNsTmF035ff7o6hMwB5H8M+GYXxR8DxVPLjzTCzA4fesebjbgmxkVUhvkjgwvGJIEZDqy4M0jS3LVI6IhLKCyHzR8ycpiF6sdwIArM/hWXJ+SmSml5XlGrffX6gR9KwUiPVADCrVIfjF8J0jSnOmECVumNtXqJxznDNio9x3DySBx2yWu1P9wO+E3hjNxg4jr2Nb3oanTFVGXidbYvpjB8MbWKcheWsqy1UZhcCbPBO8zhFsoYLyi0Lxwv5PIsLNBzsI89fANOey5IwIqfgje0+sxt/SmxP8uRyv6yuS1EDxBQWASPF8+ktSrsGQmAuNJ1nbOoRnaGP+mPDWo8Yc1oB5/qNuXflBAfVm7F3jIbgOBiVtTTVRtUSY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: jonnydyer/pypropep
