sudo: false
language: python
python:
    - "2.7"
      #    - "3.3"
      #    - "3.4"  
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls

# install: pip install tox-travis
# script: tox
