sudo: false
language: python
python:
- '2.7'
- '3.5'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: jonnyd
  password:
    secure: LcYPn+PsgvNZR5BgID5DUQNpoSFQAGDFGI2T4NyKk64xwXQw534rU+McsRc6tGdhy5cLsFH2pZR63gnaWk5yidMqttYYK5MeItZhBYxtoY8rB9cJp0BQtjOB9xXoHQVTwwzbe2lLl5EJuhQvTH6N2Qa/0RMiP98hATLko/0LA0JcQ91Wochox/0Eoa/KJ931HzcHm3zIEFYoxvARq4d1ZL/VMM8o1ErecNRegre2FmOzXR/bS2/ewBLdJujH2+5KlUeLVBPW8X4qCgfJgog3nMKjjfn4TWsQLa64PZ5TLCSItY6NtJ8l/F5gIenOoovHp/LsTGF4jeKEoKt5Zv9jmxXC2mQ0FJVr5tpWBIZH/gh2g63/nHlaLU7ehUXUJiOard7tb/SpJd7ZiV5HK2Y/YBTVhQ6MdUsJ2tIjIP7Hl49WvH2oPNoSP5pEcURGO6uSEWw4GH2OO0yNVGpeOphbZHLkeBux5InuuNF06u8RInlWhwZQQpH2R5ANW5WIXce9CbNPDBUKYajPFZ+ePXZTLHYKQPF15pJtVR3UbXZZnjd+uZGrDvspvsODfVQRdYzut8CuT4cIfE45mLOdjCdItnEg83XPECjaLs595nllf5OY30IPuCjIE0ZSarwJuby44au41mhaAO/4thyxc5rp3cZYzahyAHFyYwl6EoI2ak4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: jonnydyer/pypropep
